# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  apt:
    packages:
    - pandoc

before_install:
  - python3 -m pip --user || wget -qO- https://bootstrap.pypa.io/get-pip.py | python3 --user
  - python3 -m pip install --user jupyter
  - python3 -m pip install --user jupyter-nbconvert

    