# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  apt:
    packages:
    - pandoc

before_install:
  -  python -m pip || wget -qO- https://bootstrap.pypa.io/get-pip.py | python
  - python3 -m pip install jupyter
  - python3 -m pip install jupyter-nbconvert

    