# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  apt:
    packages:
    - pandoc

before_install:
  - sudo python3 -m pip || wget -qO- https://bootstrap.pypa.io/get-pip.py | sudo python3
  - python3 -m pip install --user jupyter
  - python3 -m pip install --user jupyter-nbconvert

    